using Content.Shared._DV.ItemQuality;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._DV.ItemQuality.UI;

/// <summary>
/// The fragment control that displays inside the PDA for the appraiser archive cartridge.
/// Shows a scrollable list of scanned items with quality, condition, and effectiveness.
/// Clicking an entry expands it to show detailed statistics.
/// Entries can be favorited (star toggle) or removed.
/// Stats are shown as word-based descriptions by default.
/// A "Decrypt" button opens an inline timing QTE minigame to reveal exact numbers.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AppraiserArchiveUiFragment : BoxContainer
{
    public event Action<AppraiserArchiveAction, int>? OnAction;

    /// <summary>
    /// Tracks which entry index is currently expanded (-1 = none).
    /// </summary>
    private int _expandedIndex = -1;

    /// <summary>
    /// Current entries reference for UI rebuild after QTE.
    /// </summary>
    private List<AppraiserArchiveEntry>? _currentEntries;

    // ─── Decrypt QTE state ───
    private int _decryptingIndex = -1;
    private DecryptChallenge? _challenge;
    private int _qteRound;
    private int _qteHits;
    private bool[] _roundResults = Array.Empty<bool>();
    private BoxContainer? _qteEntryContainer; // parent for in-place QTE panel swap
    private const int QteRoundsTotal = 4;
    private const int QteHitsRequired = 3;
    private static readonly Random Rng = new();

    private enum ChallengeType
    {
        SignalLock,     // Single marker + static zone
        CounterSweep,  // Two markers moving opposite directions, both must be in zone
        DriftLock,     // Single marker + slowly drifting zone
    }

    public AppraiserArchiveUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        ClearButton.OnPressed += _ => OnAction?.Invoke(AppraiserArchiveAction.ClearAll, -1);
    }

    public void UpdateState(List<AppraiserArchiveEntry> entries)
    {
        _currentEntries = entries;
        EntryContainer.RemoveAllChildren();

        for (var i = 0; i < entries.Count; i++)
        {
            var entry = entries[i];
            var index = i;

            // ─── Main row ───
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(4, 2),
            };

            // Favorite star button
            var favButton = new Button
            {
                Text = entry.IsFavorite ? "[*]" : "[ ]",
                MinWidth = 30,
                StyleClasses = { "OpenBoth" },
            };
            favButton.OnPressed += _ => OnAction?.Invoke(AppraiserArchiveAction.ToggleFavorite, index);

            // Item info label with quality color and condition
            var qualityColor = SharedItemQualitySystem.GetQualityColor(entry.Quality);
            var wearColor = SharedItemQualitySystem.GetWearColor(entry.Wear);
            var qualityName = Loc.GetString("item-quality-tier-" + entry.Quality.ToString().ToLower());
            var wearPercent = (int) MathF.Round(entry.Wear * 100f);
            var effectivePercent = (int) MathF.Round(entry.EffectiveMultiplier * 100f);

            // Category prefix (escaped for markup)
            var categoryIcon = entry.ItemCategory switch
            {
                "WeaponRanged" => "(R) ",
                "WeaponMelee" => "(M) ",
                "WeaponHybrid" => "(H) ",
                "Armor" => "(A) ",
                _ => "",
            };

            var infoLabel = new RichTextLabel
            {
                HorizontalExpand = true,
                Margin = new Thickness(4, 0),
            };

            var msg = new FormattedMessage();
            msg.AddMarkupOrThrow($"[bold]{categoryIcon}{FormattedMessage.EscapeText(entry.ItemName)}[/bold] ");
            msg.AddMarkupOrThrow($"[color={qualityColor}]{qualityName}[/color] ");
            msg.AddMarkupOrThrow($"[color={wearColor}]{wearPercent}%[/color] ");
            msg.AddMarkupOrThrow($"({effectivePercent}%)");
            infoLabel.SetMessage(msg);

            // Remove button
            var removeButton = new TextureButton();
            removeButton.AddStyleClass("windowCloseButton");
            removeButton.OnPressed += _ => OnAction?.Invoke(AppraiserArchiveAction.RemoveEntry, index);

            row.AddChild(favButton);
            row.AddChild(infoLabel);
            row.AddChild(removeButton);

            // Make the row clickable to expand/collapse
            var entryContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                RectClipContent = true,
            };

            // Click handler on the info label area
            var clickButton = new Button
            {
                HorizontalExpand = true,
                StyleClasses = { "OpenBoth" },
                Margin = new Thickness(0),
            };
            clickButton.RemoveAllChildren();
            clickButton.AddChild(row);
            var capturedIndex = index;
            clickButton.OnPressed += _ =>
            {
                // Cancel any active QTE if clicking a different entry
                if (_decryptingIndex >= 0 && _decryptingIndex != capturedIndex)
                    CancelDecrypt();

                _expandedIndex = _expandedIndex == capturedIndex ? -1 : capturedIndex;
                UpdateState(entries);
            };

            entryContainer.AddChild(clickButton);

            // ─── Expanded detail panel ───
            if (_expandedIndex == index)
            {
                if (_decryptingIndex == index)
                {
                    var qtePanel = BuildQtePanel(entry);
                    entryContainer.AddChild(qtePanel);
                    _qteEntryContainer = entryContainer; // store for in-place rebuild
                }
                else
                {
                    var detailPanel = BuildDetailPanel(entry, index);
                    entryContainer.AddChild(detailPanel);
                }
            }

            EntryContainer.AddChild(entryContainer);
        }

        if (entries.Count == 0)
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("appraiser-archive-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(8),
            };
            EntryContainer.AddChild(emptyLabel);
        }
    }

    /// <summary>
    /// Builds the expandable detail panel for an archive entry.
    /// Shows word-based descriptions by default, exact numbers when decrypted.
    /// </summary>
    private PanelContainer BuildDetailPanel(AppraiserArchiveEntry entry, int index)
    {
        var panel = new PanelContainer
        {
            StyleClasses = { "BackgroundDark" },
            Margin = new Thickness(8, 2, 4, 4),
            HorizontalExpand = true,
            RectClipContent = true,
        };

        var detailBox = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(6),
            RectClipContent = true,
        };

        // ─── Description (italic gray, in a bordered frame to prevent overflow) ───
        if (!string.IsNullOrEmpty(entry.ItemDescription))
        {
            var descFrame = new PanelContainer
            {
                StyleClasses = { "BackgroundDark" },
                Margin = new Thickness(0, 2, 0, 4),
                HorizontalExpand = true,
                RectClipContent = true,
            };
            var descInner = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                Margin = new Thickness(6, 4),
                HorizontalExpand = true,
            };
            var descLabel = new RichTextLabel { HorizontalExpand = true };
            var descMsg = new FormattedMessage();
            descMsg.AddMarkupOrThrow($"[italic][color=#aaaaaa]{FormattedMessage.EscapeText(entry.ItemDescription)}[/color][/italic]");
            descLabel.SetMessage(descMsg);
            descInner.AddChild(descLabel);
            descFrame.AddChild(descInner);
            detailBox.AddChild(descFrame);
        }

        // ─── Wear & Effectiveness summary ───
        var wearPercent = (int) MathF.Round(entry.Wear * 100f);
        var effectivePercent = (int) MathF.Round(entry.EffectiveMultiplier * 100f);
        var wearColor = SharedItemQualitySystem.GetWearColor(entry.Wear);
        var effColor = entry.EffectiveMultiplier >= 1.0f ? "#50ff50" : "#ff5050";
        AddMarkupLine(detailBox,
            Loc.GetString("appraiser-archive-wear-info",
                ("percent", $"[color={wearColor}]{wearPercent}[/color]"),
                ("effective", $"[color={effColor}]{effectivePercent}[/color]")));

        // ─── Category ───
        var categoryName = GetLocalizedCategory(entry.ItemCategory);
        AddMarkupLine(detailBox,
            $"[color=#8888cc]{Loc.GetString("appraiser-archive-type", ("type", categoryName))}[/color]");

        // ═══ Fire mode — ALWAYS visible regardless of decryption ═══
        if (entry.GunFireMode != null)
        {
            var modeName = Loc.GetString("appraiser-archive-firemode-" + entry.GunFireMode);
            AddMarkupLine(detailBox, $"[bold]{Loc.GetString("appraiser-archive-gun-mode", ("mode", modeName))}[/bold]");
        }

        if (entry.ShotsPerBurst != null)
        {
            AddMarkupLine(detailBox, Loc.GetString("appraiser-archive-gun-burst",
                ("value", entry.ShotsPerBurst.Value)));
        }

        // ═══ Weapon Stats section ═══
        var hasWeaponStats = entry.MeleeDamage != null || entry.GunMinAngle != null || entry.GunFireMode != null;
        if (hasWeaponStats)
        {
            AddSectionHeader(detailBox, Loc.GetString("appraiser-archive-section-weapon"));

            if (entry.IsDecrypted)
            {
                // Exact numbers (decrypted)
                BuildWeaponStatsExact(detailBox, entry);
            }
            else
            {
                // Word-based descriptions
                BuildWeaponStatsWords(detailBox, entry);
            }
        }

        // ═══ Condition section ═══
        if (entry.CanJam || entry.IsJammed)
        {
            AddSectionHeader(detailBox, Loc.GetString("appraiser-archive-section-condition"));

            if (entry.IsJammed)
                AddMarkupLine(detailBox, $"[color=#ff5050]{FormattedMessage.EscapeText(Loc.GetString("appraiser-archive-jammed"))}[/color]");
            else if (entry.CanJam)
                AddMarkupLine(detailBox, $"[color=#ffaa50]{FormattedMessage.EscapeText(Loc.GetString("appraiser-archive-jam-capable"))}[/color]");
        }

        // ═══ Armor section ═══
        if (entry.ArmorCoefficients is { Count: > 0 })
        {
            AddSectionHeader(detailBox, Loc.GetString("appraiser-archive-section-armor"));

            if (entry.IsDecrypted)
            {
                BuildArmorStatsExact(detailBox, entry);
            }
            else
            {
                BuildArmorStatsWords(detailBox, entry);
            }
        }

        // ═══ Extra stats (slowdown, explosion, stamina) ═══
        var hasExtras = entry.SpeedModifierPercent != null ||
                        entry.ExplosionResistance != null ||
                        entry.StaminaResistance != null;

        if (hasExtras)
        {
            AddSectionHeader(detailBox, Loc.GetString("appraiser-archive-section-extras"));

            if (entry.IsDecrypted)
            {
                BuildExtraStatsExact(detailBox, entry);
            }
            else
            {
                BuildExtraStatsWords(detailBox, entry);
            }
        }

        // ═══ Price estimate section ═══
        if (entry.EstimatedPriceMin != null && entry.EstimatedPriceMax != null)
        {
            AddSectionHeader(detailBox, Loc.GetString("appraiser-archive-section-price"));
            AddMarkupLine(detailBox, Loc.GetString("appraiser-archive-price-range",
                ("min", entry.EstimatedPriceMin.Value),
                ("max", entry.EstimatedPriceMax.Value)));
        }

        // ═══ Decrypt button (if not yet decrypted) ═══
        if (!entry.IsDecrypted)
        {
            var decryptButton = new Button
            {
                Text = Loc.GetString("appraiser-archive-decrypt-button"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 6, 0, 2),
                StyleClasses = { "OpenBoth" },
                MinWidth = 120,
            };
            var capturedIdx = index;
            decryptButton.OnPressed += _ => StartDecrypt(capturedIdx);
            detailBox.AddChild(decryptButton);
        }

        panel.AddChild(detailBox);
        return panel;
    }

    // ═══ Word-based stat builders ═══

    private static void BuildWeaponStatsWords(BoxContainer parent, AppraiserArchiveEntry entry)
    {
        // Melee damage as combat power rating
        if (entry.MeleeDamage != null)
        {
            var rating = GetDamageRating(entry.AdjustedMeleeDamage ?? entry.MeleeDamage.Value);
            var color = GetDamageColor(entry.AdjustedMeleeDamage ?? entry.MeleeDamage.Value);
            AddMarkupLine(parent,
                Loc.GetString("item-quality-examine-damage",
                    ("rating", $"[color={color}]{Loc.GetString(rating)}[/color]")));
        }
    }

    private static void BuildWeaponStatsExact(BoxContainer parent, AppraiserArchiveEntry entry)
    {
        // Melee damage (base -> adjusted)
        if (entry.MeleeDamage != null && entry.AdjustedMeleeDamage != null)
        {
            AddMarkupLine(parent, Loc.GetString("appraiser-lens-melee-damage",
                ("base", (int) MathF.Round(entry.MeleeDamage.Value)),
                ("adjusted", (int) MathF.Round(entry.AdjustedMeleeDamage.Value))));

            // Per-type breakdown
            if (entry.MeleeDamageTypes is { Count: > 0 })
            {
                foreach (var (type, value) in entry.MeleeDamageTypes)
                {
                    var typeName = Loc.GetString("armor-damage-type-" + type.ToLower());
                    AddMarkupLine(parent, $"[color=#aaaaaa]  {FormattedMessage.EscapeText(typeName)}: {(int) MathF.Round(value)}[/color]");
                }
            }
        }

        // Gun spread
        if (entry.GunMinAngle != null && entry.GunMaxAngle != null)
        {
            AddMarkupLine(parent, Loc.GetString("appraiser-archive-gun-spread",
                ("min", MathF.Round(entry.GunMinAngle.Value, 1)),
                ("max", MathF.Round(entry.GunMaxAngle.Value, 1))));
        }

        // Projectile speed
        if (entry.ProjectileSpeed != null)
        {
            AddMarkupLine(parent, Loc.GetString("appraiser-archive-gun-speed",
                ("value", (int) MathF.Round(entry.ProjectileSpeed.Value))));
        }
    }

    private static void BuildArmorStatsWords(BoxContainer parent, AppraiserArchiveEntry entry)
    {
        if (entry.ArmorCoefficients != null)
        {
            foreach (var coeff in entry.ArmorCoefficients)
            {
                var armorType = Loc.GetString("armor-damage-type-" + coeff.Key.ToLower());
                var protectPct = (1f - coeff.Value) * 100f;
                var rating = GetProtectionRating(protectPct);
                var color = GetProtectionColor(protectPct);
                AddMarkupLine(parent, Loc.GetString("armor-coefficient-description",
                    ("type", armorType),
                    ("rating", $"[color={color}]{Loc.GetString(rating)}[/color]")));
            }
        }
    }

    private static void BuildArmorStatsExact(BoxContainer parent, AppraiserArchiveEntry entry)
    {
        if (entry.ArmorCoefficients != null)
        {
            foreach (var coeff in entry.ArmorCoefficients)
            {
                var armorType = Loc.GetString("armor-damage-type-" + coeff.Key.ToLower());
                var protection = (int) MathF.Round((1f - coeff.Value) * 100);
                AddMarkupLine(parent, Loc.GetString("armor-coefficient-value",
                    ("type", armorType),
                    ("value", protection)));
            }
        }

        if (entry.ArmorFlatReduction is { Count: > 0 })
        {
            foreach (var flat in entry.ArmorFlatReduction)
            {
                var armorType = Loc.GetString("armor-damage-type-" + flat.Key.ToLower());
                AddMarkupLine(parent, Loc.GetString("armor-reduction-value",
                    ("type", armorType),
                    ("value", (int) MathF.Round(flat.Value))));
            }
        }
    }

    private static void BuildExtraStatsWords(BoxContainer parent, AppraiserArchiveEntry entry)
    {
        if (entry.SpeedModifierPercent != null)
        {
            var pct = entry.SpeedModifierPercent.Value;
            var isSlowdown = pct > 0;
            var rating = GetSpeedRatingWord(MathF.Abs(pct), isSlowdown);
            var color = GetSpeedColor(MathF.Abs(pct), isSlowdown);
            AddMarkupLine(parent, Loc.GetString("appraiser-archive-slowdown",
                ("rating", $"[color={color}]{Loc.GetString(rating)}[/color]")));
        }

        if (entry.ExplosionResistance != null)
        {
            var rating = GetProtectionRating(entry.ExplosionResistance.Value);
            var color = GetProtectionColor(entry.ExplosionResistance.Value);
            AddMarkupLine(parent, Loc.GetString("appraiser-archive-explosion",
                ("rating", $"[color={color}]{Loc.GetString(rating)}[/color]")));
        }

        if (entry.StaminaResistance != null)
        {
            var rating = GetProtectionRating(entry.StaminaResistance.Value);
            var color = GetProtectionColor(entry.StaminaResistance.Value);
            AddMarkupLine(parent, Loc.GetString("appraiser-archive-stamina",
                ("rating", $"[color={color}]{Loc.GetString(rating)}[/color]")));
        }
    }

    private static void BuildExtraStatsExact(BoxContainer parent, AppraiserArchiveEntry entry)
    {
        if (entry.SpeedModifierPercent != null)
        {
            var pct = entry.SpeedModifierPercent.Value;
            var label = pct > 0 ? $"[color=#ff8050]Speed: -{MathF.Round(MathF.Abs(pct), 1)}%[/color]"
                                : $"[color=#50ff50]Speed: +{MathF.Round(MathF.Abs(pct), 1)}%[/color]";
            AddMarkupLine(parent, label);
        }

        if (entry.ExplosionResistance != null)
        {
            AddMarkupLine(parent,
                $"[color=orange]Explosion[/color]: [color=lightblue]{MathF.Round(entry.ExplosionResistance.Value, 1)}%[/color] resistance");
        }

        if (entry.StaminaResistance != null)
        {
            AddMarkupLine(parent,
                $"[color=cyan]Stamina[/color]: [color=lightblue]{MathF.Round(entry.StaminaResistance.Value, 1)}%[/color] resistance");
        }
    }

    // ═══ Decrypt QTE ═══

    private void StartDecrypt(int index)
    {
        _decryptingIndex = index;
        _qteRound = 0;
        _qteHits = 0;
        _roundResults = Array.Empty<bool>();
        if (_currentEntries != null)
            UpdateState(_currentEntries);
    }

    private void CancelDecrypt()
    {
        _decryptingIndex = -1;
        _challenge = null;
        _roundResults = Array.Empty<bool>();
        _qteEntryContainer = null;
    }

    private static ChallengeType GetChallengeForRound(int round)
    {
        return round switch
        {
            0 => ChallengeType.SignalLock,
            1 => Rng.Next(2) == 0 ? ChallengeType.SignalLock : ChallengeType.DriftLock,
            2 => Rng.Next(2) == 0 ? ChallengeType.DriftLock : ChallengeType.CounterSweep,
            _ => ChallengeType.CounterSweep,
        };
    }

    private PanelContainer BuildQtePanel(AppraiserArchiveEntry entry)
    {
        var panel = new PanelContainer
        {
            StyleClasses = { "BackgroundDark" },
            Margin = new Thickness(8, 2, 4, 4),
            HorizontalExpand = true,
        };

        var box = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(6),
        };

        // Header
        AddMarkupLine(box,
            $"[bold][color=#00cc88]== {Loc.GetString("appraiser-archive-decrypt-title")} ==[/color][/bold]");

        // Round progress (# = hit, X = miss, > = current, o = remaining)
        var progressMsg = new FormattedMessage();
        for (var i = 0; i < QteRoundsTotal; i++)
        {
            if (i < _roundResults.Length)
            {
                progressMsg.AddMarkupOrThrow(_roundResults[i]
                    ? "[color=#00ff88]#[/color] "
                    : "[color=#ff4444]X[/color] ");
            }
            else if (i == _qteRound)
            {
                progressMsg.AddMarkupOrThrow("[color=#ffcc00]>[/color] ");
            }
            else
            {
                progressMsg.AddMarkupOrThrow("[color=#444466]o[/color] ");
            }
        }

        var progressLabel = new RichTextLabel { HorizontalExpand = true };
        progressLabel.SetMessage(progressMsg);
        box.AddChild(progressLabel);

        // Challenge type label
        var challengeType = GetChallengeForRound(_qteRound);
        var typeName = challengeType switch
        {
            ChallengeType.SignalLock => Loc.GetString("appraiser-archive-decrypt-type-signal"),
            ChallengeType.CounterSweep => Loc.GetString("appraiser-archive-decrypt-type-counter"),
            ChallengeType.DriftLock => Loc.GetString("appraiser-archive-decrypt-type-drift"),
            _ => "",
        };
        AddMarkupLine(box, $"[color=#88aacc]{typeName}[/color]");

        // Instruction varies by type
        var instruction = challengeType switch
        {
            ChallengeType.CounterSweep => Loc.GetString("appraiser-archive-decrypt-instruction-counter"),
            ChallengeType.DriftLock => Loc.GetString("appraiser-archive-decrypt-instruction-drift"),
            _ => Loc.GetString("appraiser-archive-decrypt-instruction"),
        };
        AddMarkupLine(box, $"[color=#667788]{instruction}[/color]");

        // Create challenge control
        _challenge = new DecryptChallenge();
        var zoneCenter = 0.2f + (float) Rng.NextDouble() * 0.6f;
        var zoneSize = 0.20f - _qteRound * 0.03f;
        var speed = 0.5f + _qteRound * 0.2f;

        _challenge.Configure(challengeType, zoneCenter, zoneSize, speed, _qteRound);
        _challenge.Margin = new Thickness(0, 4, 0, 4);
        _challenge.OnAttempt += OnQteAttempt;
        box.AddChild(_challenge);

        // Cancel button
        var cancelButton = new Button
        {
            Text = Loc.GetString("appraiser-archive-decrypt-cancel"),
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(0, 2, 0, 0),
            StyleClasses = { "OpenBoth" },
            MinWidth = 60,
        };
        cancelButton.OnPressed += _ =>
        {
            CancelDecrypt();
            if (_currentEntries != null)
                UpdateState(_currentEntries);
        };
        box.AddChild(cancelButton);

        panel.AddChild(box);
        return panel;
    }

    private void OnQteAttempt(bool success)
    {
        var newResults = new bool[_roundResults.Length + 1];
        Array.Copy(_roundResults, newResults, _roundResults.Length);
        newResults[^1] = success;
        _roundResults = newResults;

        if (success)
            _qteHits++;

        _qteRound++;

        // Early termination: already succeeded or impossible to succeed
        var remainingRounds = QteRoundsTotal - _qteRound;
        var hitsNeeded = QteHitsRequired - _qteHits;

        if (_qteRound >= QteRoundsTotal || _qteHits >= QteHitsRequired || hitsNeeded > remainingRounds)
        {
            if (_qteHits >= QteHitsRequired && _decryptingIndex >= 0)
            {
                OnAction?.Invoke(AppraiserArchiveAction.DecryptEntry, _decryptingIndex);
            }

            CancelDecrypt();

            // Full rebuild only when QTE finishes
            if (_currentEntries != null)
                UpdateState(_currentEntries);
            return;
        }

        // Intermediate round: swap QTE panel in-place (avoid full UI rebuild)
        if (_qteEntryContainer != null
            && _currentEntries != null
            && _expandedIndex >= 0
            && _expandedIndex < _currentEntries.Count
            && _qteEntryContainer.ChildCount > 1)
        {
            var lastChild = _qteEntryContainer.GetChild(_qteEntryContainer.ChildCount - 1);
            _qteEntryContainer.RemoveChild(lastChild);
            var newPanel = BuildQtePanel(_currentEntries[_expandedIndex]);
            _qteEntryContainer.AddChild(newPanel);
        }
        else if (_currentEntries != null)
        {
            UpdateState(_currentEntries);
        }
    }

    // ═══ Rating helper methods (client-side duplicates of server logic) ═══

    private static string GetProtectionRating(float percent)
    {
        return percent switch
        {
            >= 50f => "armor-rating-exceptional",
            >= 35f => "armor-rating-good",
            >= 20f => "armor-rating-moderate",
            >= 10f => "armor-rating-weak",
            >= 1f => "armor-rating-negligible",
            _ => "armor-rating-none",
        };
    }

    private static string GetProtectionColor(float percent)
    {
        return percent switch
        {
            >= 50f => "#50ff50",
            >= 35f => "#b0ff50",
            >= 20f => "#ffff50",
            >= 10f => "#ff8050",
            >= 1f => "#ff5050",
            _ => "#808080",
        };
    }

    private static string GetDamageRating(float totalDamage)
    {
        return totalDamage switch
        {
            >= 25f => "item-quality-damage-devastating",
            >= 18f => "item-quality-damage-powerful",
            >= 10f => "item-quality-damage-moderate",
            >= 5f => "item-quality-damage-light",
            _ => "item-quality-damage-negligible",
        };
    }

    private static string GetDamageColor(float totalDamage)
    {
        return totalDamage switch
        {
            >= 25f => "#ff3030",
            >= 18f => "#ff8050",
            >= 10f => "#ffff50",
            >= 5f => "#b0ff50",
            _ => "#808080",
        };
    }

    private static string GetSpeedRatingWord(float percentEffect, bool isSlowdown)
    {
        if (isSlowdown)
        {
            return percentEffect switch
            {
                >= 25f => "clothing-speed-rating-severe-slowdown",
                >= 15f => "clothing-speed-rating-significant-slowdown",
                >= 8f => "clothing-speed-rating-moderate-slowdown",
                >= 3f => "clothing-speed-rating-light-slowdown",
                _ => "clothing-speed-rating-negligible-slowdown",
            };
        }

        return percentEffect switch
        {
            >= 25f => "clothing-speed-rating-major-boost",
            >= 15f => "clothing-speed-rating-significant-boost",
            >= 8f => "clothing-speed-rating-moderate-boost",
            >= 3f => "clothing-speed-rating-light-boost",
            _ => "clothing-speed-rating-negligible-boost",
        };
    }

    private static string GetSpeedColor(float percentEffect, bool isSlowdown)
    {
        if (isSlowdown)
        {
            return percentEffect switch
            {
                >= 25f => "#ff3030",
                >= 15f => "#ff6050",
                >= 8f => "#ff8050",
                >= 3f => "#ffaa50",
                _ => "#ffcc50",
            };
        }

        return percentEffect switch
        {
            >= 25f => "#50ff50",
            >= 15f => "#80ff50",
            >= 8f => "#b0ff50",
            >= 3f => "#d0ff50",
            _ => "#e0ff80",
        };
    }

    // ═══ Utility methods ═══

    private static string GetLocalizedCategory(string category)
    {
        return category switch
        {
            "WeaponRanged" => Loc.GetString("appraiser-archive-category-ranged"),
            "WeaponMelee" => Loc.GetString("appraiser-archive-category-melee"),
            "WeaponHybrid" => Loc.GetString("appraiser-archive-category-hybrid"),
            "Armor" => Loc.GetString("appraiser-archive-category-armor"),
            _ => Loc.GetString("appraiser-archive-category-item"),
        };
    }

    private static void AddSectionHeader(BoxContainer parent, string text)
    {
        var label = new RichTextLabel
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 4, 0, 0),
        };
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow($"[bold][color=#88aacc]{FormattedMessage.EscapeText(text)}[/color][/bold]");
        label.SetMessage(msg);
        parent.AddChild(label);
    }

    private static void AddMarkupLine(BoxContainer parent, string markup)
    {
        var label = new RichTextLabel { HorizontalExpand = true };
        var msg = new FormattedMessage();
        try
        {
            msg.AddMarkupOrThrow(markup);
        }
        catch (Exception)
        {
            // Fallback: render as plain text if markup is invalid.
            msg.AddText(markup);
        }
        label.SetMessage(msg);
        parent.AddChild(label);
    }

    // ═══ Decrypt challenge inline control ═══

    /// <summary>
    /// Multi-type decryption challenge for PDA archive entries.
    /// Supports three challenge modes:
    /// - SignalLock: Single marker bouncing, click when in green zone.
    /// - CounterSweep: Two markers moving opposite, click when both in zone.
    /// - DriftLock: Single marker bouncing, zone slowly drifts.
    /// Features visual noise, pulsing zones, and marker glow effects.
    /// </summary>
    private sealed class DecryptChallenge : Control
    {
        public event Action<bool>? OnAttempt;

        private ChallengeType _type;
        private bool _active;

        // Primary marker
        private float _marker1;
        private float _speed1;
        private int _dir1 = 1;

        // Secondary marker (CounterSweep only)
        private float _marker2;
        private float _speed2;
        private int _dir2 = -1;

        // Zone
        private float _zoneStart;
        private float _zoneEnd;
        private float _zoneSpeed;
        private int _zoneDir = 1;
        private float _zoneCenter;
        private float _zoneSize;

        // Visual effects
        private float _pulseTimer;
        private float _noiseTimer;
        private readonly float[] _noiseSeg = new float[24];
        private readonly Color[] _noiseCol = new Color[24];

        public DecryptChallenge()
        {
            MinSize = new System.Numerics.Vector2(0, 32);
            HorizontalExpand = true;
            MouseFilter = MouseFilterMode.Stop;
            RegenerateNoise();
        }

        private void RegenerateNoise()
        {
            for (var i = 0; i < _noiseSeg.Length; i++)
            {
                _noiseSeg[i] = (float) Rng.NextDouble();
                var b = 0.04f + (float) Rng.NextDouble() * 0.08f;
                _noiseCol[i] = Rng.Next(2) == 0
                    ? new Color(b, b * 1.5f, b * 0.3f)
                    : new Color(b * 0.3f, b, b * 1.5f);
            }
        }

        public void Configure(ChallengeType type, float zoneCenter, float zoneSize, float speed, int round)
        {
            _type = type;
            _zoneSize = Math.Max(zoneSize, 0.06f);
            _zoneCenter = Math.Clamp(zoneCenter, _zoneSize / 2 + 0.02f, 1f - _zoneSize / 2 - 0.02f);
            _zoneStart = _zoneCenter - _zoneSize / 2;
            _zoneEnd = _zoneCenter + _zoneSize / 2;

            _marker1 = 0;
            _dir1 = 1;
            _speed1 = speed;

            switch (type)
            {
                case ChallengeType.CounterSweep:
                    _marker2 = 1;
                    _dir2 = -1;
                    _speed2 = speed * (0.85f + round * 0.1f);
                    break;
                case ChallengeType.DriftLock:
                    _zoneSpeed = 0.06f + round * 0.03f;
                    _zoneDir = Rng.Next(2) == 0 ? 1 : -1;
                    break;
            }

            _active = true;
            _pulseTimer = 0;
            _noiseTimer = 0;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            if (!_active)
                return;

            var dt = args.DeltaSeconds;
            _pulseTimer += dt * 3f;
            _noiseTimer += dt;

            if (_noiseTimer > 0.12f)
            {
                _noiseTimer = 0;
                RegenerateNoise();
            }

            // Move primary marker
            _marker1 += _speed1 * _dir1 * dt;
            if (_marker1 >= 1) { _marker1 = 1; _dir1 = -1; }
            else if (_marker1 <= 0) { _marker1 = 0; _dir1 = 1; }

            // Move secondary marker (CounterSweep)
            if (_type == ChallengeType.CounterSweep)
            {
                _marker2 += _speed2 * _dir2 * dt;
                if (_marker2 >= 1) { _marker2 = 1; _dir2 = -1; }
                else if (_marker2 <= 0) { _marker2 = 0; _dir2 = 1; }
            }

            // Drift zone (DriftLock)
            if (_type == ChallengeType.DriftLock)
            {
                _zoneCenter += _zoneSpeed * _zoneDir * dt;
                if (_zoneCenter + _zoneSize / 2 >= 0.98f)
                {
                    _zoneCenter = 0.98f - _zoneSize / 2;
                    _zoneDir = -1;
                }
                else if (_zoneCenter - _zoneSize / 2 <= 0.02f)
                {
                    _zoneCenter = 0.02f + _zoneSize / 2;
                    _zoneDir = 1;
                }

                _zoneStart = _zoneCenter - _zoneSize / 2;
                _zoneEnd = _zoneCenter + _zoneSize / 2;
            }
        }

        protected override void KeyBindDown(GUIBoundKeyEventArgs args)
        {
            base.KeyBindDown(args);
            if (!_active || args.Function != EngineKeyFunctions.UIClick)
                return;

            args.Handle();
            _active = false;

            bool hit;
            switch (_type)
            {
                case ChallengeType.CounterSweep:
                    hit = _marker1 >= _zoneStart && _marker1 <= _zoneEnd
                       && _marker2 >= _zoneStart && _marker2 <= _zoneEnd;
                    break;
                default:
                    hit = _marker1 >= _zoneStart && _marker1 <= _zoneEnd;
                    break;
            }

            OnAttempt?.Invoke(hit);
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var w = (float) PixelWidth;
            var h = (float) PixelHeight;

            // Dark terminal background
            handle.DrawRect(new UIBox2(0, 0, w, h), new Color(0.04f, 0.06f, 0.1f));

            // Background noise segments
            var segW = w / _noiseSeg.Length;
            for (var i = 0; i < _noiseSeg.Length; i++)
            {
                var sx = i * segW;
                var sh = _noiseSeg[i] * h * 0.3f;
                var sy = (h - sh) / 2;
                handle.DrawRect(new UIBox2(sx, sy, sx + segW - 1, sy + sh), _noiseCol[i]);
            }

            // Zone with pulse glow
            var pulse = 0.5f + 0.15f * MathF.Sin(_pulseTimer);
            var zx1 = _zoneStart * w;
            var zx2 = _zoneEnd * w;
            handle.DrawRect(new UIBox2(zx1, 1, zx2, h - 1),
                new Color(0.05f, pulse * 0.4f, 0.15f, 0.7f));

            // Zone edge highlights
            var edgeW = 2f * UIScale;
            handle.DrawRect(new UIBox2(zx1, 1, zx1 + edgeW, h - 1),
                new Color(0.1f, 0.7f, 0.3f, 0.8f));
            handle.DrawRect(new UIBox2(zx2 - edgeW, 1, zx2, h - 1),
                new Color(0.1f, 0.7f, 0.3f, 0.8f));

            // For DriftLock, show zone center indicator
            if (_type == ChallengeType.DriftLock && _active)
            {
                var cx = _zoneCenter * w;
                handle.DrawRect(new UIBox2(cx - 1, 0, cx + 1, h),
                    new Color(0f, 1f, 0.5f, 0.15f));
            }

            // Primary marker (cyan glow + white line)
            DrawMarker(handle, _marker1, w, h,
                new Color(0.2f, 0.5f, 1f, 0.12f),
                new Color(0.7f, 0.9f, 1f));

            // Secondary marker for CounterSweep (orange glow + orange line)
            if (_type == ChallengeType.CounterSweep)
            {
                DrawMarker(handle, _marker2, w, h,
                    new Color(1f, 0.4f, 0.1f, 0.12f),
                    new Color(1f, 0.7f, 0.3f));
            }

            // Border
            handle.DrawRect(new UIBox2(0, 0, w, 1), new Color(0.15f, 0.2f, 0.3f));
            handle.DrawRect(new UIBox2(0, h - 1, w, h), new Color(0.15f, 0.2f, 0.3f));
            handle.DrawRect(new UIBox2(0, 0, 1, h), new Color(0.15f, 0.2f, 0.3f));
            handle.DrawRect(new UIBox2(w - 1, 0, w, h), new Color(0.15f, 0.2f, 0.3f));
        }

        private void DrawMarker(DrawingHandleScreen handle, float pos, float w, float h,
            Color glowColor, Color lineColor)
        {
            var mx = pos * w;
            var mw = 2f * UIScale;

            // Glow
            handle.DrawRect(new UIBox2(mx - mw * 4, 2, mx + mw * 4, h - 2), glowColor);
            // Line
            handle.DrawRect(new UIBox2(mx - mw, 1, mx + mw, h - 1), lineColor);
        }
    }
}
