using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._DV.ItemQuality;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._DV.ItemQuality.UI;

/// <summary>
/// Appraiser lens focusing window — two-phase immersive minigame.
/// Phase 1 (Calibration): Rotate 5 lens dials to the correct positions (combination lock).
///   Each dial provides proximity feedback via color and pitch.
/// Phase 2 (Synchronization): Timing ring challenges — a sweeping dot moves around a circle,
///   click when it's in the green zone. 5 rounds with increasing difficulty.
///   Tracks accuracy based on how close to zone center the click lands.
/// Successfully completing both phases transmits scan data to the PDA archive.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AppraiserLensWindow : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;

    private readonly SharedAudioSystem _audio;

    /// <summary>
    /// Fired when the QTE minigame is completed successfully.
    /// Passes the target EntityUid so the client system can send the scan request.
    /// </summary>
    public event Action<EntityUid>? OnAppraisalComplete;

    // ─── Dial phase ───
    private const int DialCount = 5;
    private const int Positions = 12;
    private readonly LensDial[] _dials = new LensDial[DialCount];
    private readonly int[] _targets = new int[DialCount];

    // ─── Timing ring phase ───
    private TimingRing? _timingRing;
    private int _currentTimingPhase; // which dial's timing ring we're on (0..4)
    private int _completedTimings;   // how many timing rings completed
    private bool _allDialsCorrect;

    // ─── Accuracy tracking ───
    private float _totalAccuracy;
    private int _timingAttempts;

    private EntityUid _targetEntity;
    private bool _isComplete;

    private static readonly SoundPathSpecifier LensClickSound = new("/Audio/Items/appraiser.ogg");

    /// <summary>
    /// Remembers window position across opens so the user doesn't have to re-drag each time.
    /// </summary>
    private static Vector2? _lastWindowPosition;

    public AppraiserLensWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _audio = _sysMan.GetEntitySystem<SharedAudioSystem>();

        // Save position when closing so it can be restored next time
        OnClose += () => _lastWindowPosition = GlobalPosition;

        // Create the 5 lens dials
        for (var i = 0; i < DialCount; i++)
        {
            var dial = new LensDial();
            var dialIndex = i;
            dial.OnRotated += (clockwise) => OnDialRotated(dialIndex, clockwise);
            _dials[i] = dial;
            DialsContainer.AddChild(dial);

            if (i < DialCount - 1)
                DialsContainer.AddChild(new Control { MinSize = new Vector2(6, 0) });
        }

        // Create the timing ring
        _timingRing = new TimingRing();
        _timingRing.OnAttempt += OnTimingAttempt;
        TimingRingContainer.AddChild(_timingRing);

        // Phase 2 elements hidden until dials are solved
        TimingRingContainer.Visible = false;

        StatusLabel.Text = Loc.GetString("appraiser-lens-focusing");
        PhaseLabel.Text = Loc.GetString("appraiser-lens-phase-calibration");
        SignalBar.Value = 0;
    }

    /// <summary>
    /// Opens with remembered position, or centered if first time.
    /// </summary>
    public void OpenRemembered()
    {
        if (_lastWindowPosition.HasValue)
        {
            Open();
            LayoutContainer.SetPosition(this, _lastWindowPosition.Value);
        }
        else
        {
            OpenCentered();
        }
    }

    public void SetTarget(EntityUid target, string targetName)
    {
        _targetEntity = target;
        _isComplete = false;
        _allDialsCorrect = false;
        _currentTimingPhase = 0;
        _completedTimings = 0;
        _totalAccuracy = 0f;
        _timingAttempts = 0;

        var hash = target.IsValid() ? target.GetHashCode() : 0;
        for (var i = 0; i < DialCount; i++)
        {
            _targets[i] = Math.Abs((hash >> (i * 3)) % Positions);
        }

        for (var i = 0; i < DialCount; i++)
        {
            _dials[i].CurrentPosition = 0;
            _dials[i].Proximity = GetDialProximity(0, _targets[i]);
            _dials[i].IsLocked = false;
            _dials[i].IsHighlighted = false;
        }

        // Phase 2 hidden until dials solved
        _timingRing?.SetActive(false);
        TimingRingContainer.Visible = false;
        AccuracyLabel.Visible = false;

        TargetLabel.Text = targetName;
        PhaseLabel.Text = Loc.GetString("appraiser-lens-phase-calibration");
        StatusLabel.Text = Loc.GetString("appraiser-lens-focusing");
        AccuracyLabel.Visible = false;
        ResultPanel.Visible = false;
        SignalPercent.Text = "0%";

        UpdateSignalStrength();
    }

    private void OnDialRotated(int index, bool clockwise)
    {
        if (_isComplete || _allDialsCorrect)
            return;

        if (_dials[index].IsLocked)
            return;

        if (clockwise)
            _dials[index].CurrentPosition = (_dials[index].CurrentPosition + 1) % Positions;
        else
            _dials[index].CurrentPosition = (_dials[index].CurrentPosition + Positions - 1) % Positions;

        _dials[index].Proximity = GetDialProximity(_dials[index].CurrentPosition, _targets[index]);

        // Auto-lock dials that hit the correct position
        if (_dials[index].CurrentPosition == _targets[index])
        {
            _dials[index].IsLocked = true;
            _audio.PlayGlobal(LensClickSound, Filter.Local(), false,
                AudioParams.Default.WithVolume(-2f).WithPitchScale(1.25f));
        }
        else
        {
            var proximity = _dials[index].Proximity;
            var pitch = 0.8f + proximity * 0.6f;
            _audio.PlayGlobal(LensClickSound, Filter.Local(), false,
                AudioParams.Default.WithVolume(-4f).WithPitchScale(pitch));
        }

        UpdateSignalStrength();
    }

    private static float GetDialProximity(int current, int target)
    {
        var dist = Math.Min(
            Math.Abs(current - target),
            Positions - Math.Abs(current - target));

        return dist switch
        {
            0 => 1.0f,
            1 => 0.6f,
            2 => 0.3f,
            _ => 0.0f,
        };
    }

    private void UpdateSignalStrength()
    {
        var totalProximity = 0f;
        var allCorrect = true;

        for (var i = 0; i < DialCount; i++)
        {
            totalProximity += GetDialProximity(_dials[i].CurrentPosition, _targets[i]);
            if (_dials[i].CurrentPosition != _targets[i])
                allCorrect = false;
        }

        // Signal is 0-50 for dials, 50-100 for timing rings
        var dialSignal = totalProximity / DialCount * 50f;
        var timingSignal = _completedTimings / (float) DialCount * 50f;
        var signal = dialSignal + timingSignal;
        SignalBar.Value = signal;
        SignalPercent.Text = $"{(int) signal}%";

        if (allCorrect && !_allDialsCorrect)
        {
            _allDialsCorrect = true;

            // Lock all dials
            for (var i = 0; i < DialCount; i++)
                _dials[i].IsLocked = true;

            _audio.PlayGlobal(LensClickSound, Filter.Local(), false,
                AudioParams.Default.WithVolume(-2f).WithPitchScale(1.3f));

            // Reveal Phase 2 elements
            TimingRingContainer.Visible = true;

            PhaseLabel.Text = Loc.GetString("appraiser-lens-phase-sync");
            StatusLabel.Text = Loc.GetString("appraiser-lens-timing-phase");

            StartTimingPhase();
        }
    }

    // ─── Timing ring logic ───

    private void StartTimingPhase()
    {
        if (_currentTimingPhase >= DialCount)
        {
            CompleteAppraisal();
            return;
        }

        if (_timingRing == null)
            return;

        // Each successive ring is harder: zone gets smaller, speed increases
        var zoneSize = MathF.Max(15f, 45f - _currentTimingPhase * 6f); // degrees: 45, 39, 33, 27, 21
        var speed = 120f + _currentTimingPhase * 30f; // degrees/sec: 120, 150, 180, 210, 240

        // Deterministic zone position from entity hash + phase
        var hash = _targetEntity.IsValid() ? _targetEntity.GetHashCode() : 0;
        var zoneAngle = Math.Abs((hash >> (_currentTimingPhase * 5 + 17)) % 360);

        _timingRing.Configure(zoneAngle, zoneSize, speed);
        _timingRing.SetActive(true);

        // Highlight the corresponding dial
        for (var i = 0; i < DialCount; i++)
            _dials[i].IsHighlighted = i == _currentTimingPhase;

        StatusLabel.Text = Loc.GetString("appraiser-lens-timing-round",
            ("current", _currentTimingPhase + 1), ("total", DialCount));
    }

    private void OnTimingAttempt(bool success, float accuracy)
    {
        if (_isComplete)
            return;

        _timingAttempts++;

        if (success)
        {
            _completedTimings++;
            _totalAccuracy += accuracy;

            _audio.PlayGlobal(LensClickSound, Filter.Local(), false,
                AudioParams.Default.WithVolume(-2f).WithPitchScale(1.2f + _completedTimings * 0.1f));

            // Update signal
            var dialSignal = 50f; // all dials are correct
            var timingSignal = _completedTimings / (float) DialCount * 50f;
            var signal = dialSignal + timingSignal;
            SignalBar.Value = signal;
            SignalPercent.Text = $"{(int) signal}%";

            // Show accuracy feedback
            var accPercent = (int)(accuracy * 100f);
            AccuracyLabel.Text = Loc.GetString("appraiser-lens-accuracy", ("value", accPercent));
            AccuracyLabel.Visible = true;

            _currentTimingPhase++;
            StartTimingPhase();
        }
        else
        {
            // Failed — play low pitch sound, ring resets with new speed
            _audio.PlayGlobal(LensClickSound, Filter.Local(), false,
                AudioParams.Default.WithVolume(-3f).WithPitchScale(0.6f));

            AccuracyLabel.Text = Loc.GetString("appraiser-lens-miss");
            AccuracyLabel.Visible = true;

            // Restart same phase with slightly different speed
            StartTimingPhase();
        }
    }

    private void CompleteAppraisal()
    {
        _isComplete = true;
        _timingRing?.SetActive(false);

        for (var i = 0; i < DialCount; i++)
            _dials[i].IsHighlighted = false;

        var avgAccuracy = _completedTimings > 0 ? (int)(_totalAccuracy / _completedTimings * 100f) : 0;

        PhaseLabel.Text = Loc.GetString("appraiser-lens-phase-complete");
        StatusLabel.Text = Loc.GetString("appraiser-lens-complete");
        SignalBar.Value = 100f;
        SignalPercent.Text = "100%";

        _audio.PlayGlobal(LensClickSound, Filter.Local(), false,
            AudioParams.Default.WithVolume(-2f).WithPitchScale(1.5f));

        // Show a brief success message with accuracy ratings
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("appraiser-lens-scan-transmitted"));
        msg.PushNewline();
        msg.AddMarkupOrThrow(Loc.GetString("appraiser-lens-scan-accuracy", ("value", avgAccuracy)));
        ResultLabel.SetMessage(msg);
        ResultPanel.Visible = true;
        AccuracyLabel.Visible = false;

        // Notify the client system to send scan data to the server PDA archive
        OnAppraisalComplete?.Invoke(_targetEntity);
    }

    // ═══════════════════════════════════════════════════════════════════
    //  Internal control: Timing Ring
    // ═══════════════════════════════════════════════════════════════════

    /// <summary>
    /// A ring where a dot sweeps around the circumference at a set speed.
    /// A green zone is drawn on the ring. The player must click when the dot is in the green zone.
    /// Reports accuracy (how close to center the dot was).
    /// </summary>
    private sealed class TimingRing : Control
    {
        /// <summary>
        /// Fired on click. Bool = success, Float = accuracy 0..1 (1 = perfect center).
        /// </summary>
        public event Action<bool, float>? OnAttempt;

        private bool _active;
        private float _dotAngle;     // current angle in degrees
        private float _speed;        // degrees per second
        private float _zoneCenter;   // center of the green zone in degrees
        private float _zoneHalfSize; // half-size of the green zone in degrees

        // Visual feedback for last attempt
        private float _flashTimer;
        private bool _lastHit;

        /// <summary>
        /// Cached vertex buffer for arc segment drawing — avoids allocation every frame.
        /// 6 vertices per segment (two triangles per quad).
        /// </summary>
        private readonly Vector2[] _arcVertices = new Vector2[32 * 6];

        public TimingRing()
        {
            MinSize = new Vector2(170, 170);
            MouseFilter = MouseFilterMode.Stop;
        }

        public void Configure(float zoneCenterDeg, float zoneSizeDeg, float speedDeg)
        {
            _zoneCenter = zoneCenterDeg;
            _zoneHalfSize = zoneSizeDeg / 2f;
            _speed = speedDeg;
            _dotAngle = 0f;
            _flashTimer = 0f;
        }

        public void SetActive(bool active)
        {
            _active = active;
            Visible = active;
            _dotAngle = 0f;
            _flashTimer = 0f;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            if (!_active)
                return;

            _dotAngle = (_dotAngle + _speed * args.DeltaSeconds) % 360f;

            if (_flashTimer > 0f)
                _flashTimer -= args.DeltaSeconds;
        }

        protected override void KeyBindDown(GUIBoundKeyEventArgs args)
        {
            base.KeyBindDown(args);
            if (!_active)
                return;

            if (args.Function == EngineKeyFunctions.UIClick)
            {
                args.Handle();
                var inZone = IsInZone(_dotAngle);
                var accuracy = GetAccuracy(_dotAngle);
                _flashTimer = 0.3f;
                _lastHit = inZone;
                OnAttempt?.Invoke(inZone, accuracy);
            }
        }

        private bool IsInZone(float angle)
        {
            var diff = MathF.Abs(angle - _zoneCenter);
            if (diff > 180f) diff = 360f - diff;
            return diff <= _zoneHalfSize;
        }

        /// <summary>
        /// Returns 0..1 accuracy based on how close to zone center. 1 = dead center.
        /// </summary>
        private float GetAccuracy(float angle)
        {
            var diff = MathF.Abs(angle - _zoneCenter);
            if (diff > 180f) diff = 360f - diff;
            if (diff > _zoneHalfSize) return 0f;
            return 1f - diff / _zoneHalfSize;
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);
            if (!_active)
                return;

            var scale = UIScale;
            var center = new Vector2(PixelWidth / 2f, PixelHeight / 2f);
            var outerRadius = 72f * scale;
            var innerRadius = 55f * scale;
            var midRadius = (outerRadius + innerRadius) / 2f;

            // ─── Flash feedback on attempt ───
            if (_flashTimer > 0f)
            {
                var flashAlpha = _flashTimer / 0.3f * 0.15f;
                var flashColor = _lastHit
                    ? new Color(0.2f, 1f, 0.3f, flashAlpha)
                    : new Color(1f, 0.2f, 0.2f, flashAlpha);
                handle.DrawCircle(center, outerRadius + 4 * scale, flashColor);
            }

            // ─── Background ring ───
            handle.DrawCircle(center, outerRadius, new Color(0.06f, 0.08f, 0.12f));
            handle.DrawCircle(center, innerRadius, new Color(0.03f, 0.04f, 0.06f));

            // ─── Subtle scanline effect on the ring gap ───
            for (var s = 0; s < 12; s++)
            {
                var y = center.Y - outerRadius + s * (outerRadius * 2 / 12f);
                handle.DrawLine(
                    new Vector2(center.X - outerRadius, y),
                    new Vector2(center.X + outerRadius, y),
                    new Color(0.08f, 0.12f, 0.16f, 0.15f));
            }

            // Outer/inner borders — double line for depth
            handle.DrawCircle(center, outerRadius, new Color(0.18f, 0.28f, 0.35f), false);
            handle.DrawCircle(center, outerRadius - 1 * scale, new Color(0.12f, 0.20f, 0.25f), false);
            handle.DrawCircle(center, innerRadius, new Color(0.14f, 0.22f, 0.28f), false);
            handle.DrawCircle(center, innerRadius + 1 * scale, new Color(0.10f, 0.16f, 0.22f), false);

            // ─── Green zone arc ───
            var zoneStartDeg = _zoneCenter - _zoneHalfSize;
            var zoneEndDeg = _zoneCenter + _zoneHalfSize;
            const int segments = 32;
            var outerArc = outerRadius - 1 * scale;
            var innerArc = innerRadius + 1 * scale;

            for (var i = 0; i < segments; i++)
            {
                var t0 = i / (float) segments;
                var t1 = (i + 1) / (float) segments;
                var a0 = (zoneStartDeg + (zoneEndDeg - zoneStartDeg) * t0) * MathF.PI / 180f - MathF.PI / 2f;
                var a1 = (zoneStartDeg + (zoneEndDeg - zoneStartDeg) * t1) * MathF.PI / 180f - MathF.PI / 2f;

                var dir0 = new Vector2(MathF.Cos(a0), MathF.Sin(a0));
                var dir1 = new Vector2(MathF.Cos(a1), MathF.Sin(a1));

                var outerP0 = center + dir0 * outerArc;
                var outerP1 = center + dir1 * outerArc;
                var innerP0 = center + dir0 * innerArc;
                var innerP1 = center + dir1 * innerArc;

                var vi = i * 6;
                _arcVertices[vi]     = outerP0;
                _arcVertices[vi + 1] = innerP0;
                _arcVertices[vi + 2] = outerP1;
                _arcVertices[vi + 3] = outerP1;
                _arcVertices[vi + 4] = innerP0;
                _arcVertices[vi + 5] = innerP1;
            }

            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList,
                new ReadOnlySpan<Vector2>(_arcVertices),
                new Color(0.12f, 0.60f, 0.28f, 0.4f));

            // ─── Zone center marker ───
            var centerAngleRad = _zoneCenter * MathF.PI / 180f - MathF.PI / 2f;
            var centerDir = new Vector2(MathF.Cos(centerAngleRad), MathF.Sin(centerAngleRad));
            handle.DrawLine(
                center + centerDir * (innerArc + 2 * scale),
                center + centerDir * (outerArc - 2 * scale),
                new Color(0.3f, 0.9f, 0.4f, 0.6f));

            // ─── Tick marks around the ring ───
            for (var i = 0; i < 36; i++)
            {
                var angle = i * 10f * MathF.PI / 180f - MathF.PI / 2f;
                var dir = new Vector2(MathF.Cos(angle), MathF.Sin(angle));
                var major = i % 9 == 0;
                var outer = center + dir * (outerRadius - 2 * scale);
                var inner = center + dir * (outerRadius - (major ? 10f : 4f) * scale);
                var tickCol = major
                    ? new Color(0.35f, 0.50f, 0.55f)
                    : new Color(0.20f, 0.30f, 0.35f);
                handle.DrawLine(inner, outer, tickCol);
            }

            // ─── Sweeping dot with trail ───
            var dotRad = _dotAngle * MathF.PI / 180f - MathF.PI / 2f;
            var dotDir = new Vector2(MathF.Cos(dotRad), MathF.Sin(dotRad));
            var dotPos = center + dotDir * midRadius;
            var inZone = IsInZone(_dotAngle);

            var dotColor = inZone
                ? new Color(0.3f, 1f, 0.4f)
                : new Color(1f, 0.35f, 0.25f);

            // Trail — 3 trailing dots with decreasing opacity
            for (var t = 1; t <= 3; t++)
            {
                var trailAngle = (_dotAngle - t * 8f) * MathF.PI / 180f - MathF.PI / 2f;
                var trailDir = new Vector2(MathF.Cos(trailAngle), MathF.Sin(trailAngle));
                var trailPos = center + trailDir * midRadius;
                var alpha = 0.15f / t;
                handle.DrawCircle(trailPos, (4f - t) * scale, dotColor.WithAlpha(alpha));
            }

            // Outer glow
            handle.DrawCircle(dotPos, 8f * scale, dotColor.WithAlpha(0.2f));
            // Dot
            handle.DrawCircle(dotPos, 4.5f * scale, dotColor);
            // Inner bright core
            handle.DrawCircle(dotPos, 2f * scale, Color.White.WithAlpha(0.7f));

            // ─── Center info display ───
            handle.DrawCircle(center, 16f * scale, new Color(0.05f, 0.07f, 0.10f));
            handle.DrawCircle(center, 16f * scale, new Color(0.18f, 0.28f, 0.33f), false);
            // Inner decorative ring
            handle.DrawCircle(center, 12f * scale, new Color(0.10f, 0.15f, 0.20f), false);
        }
    }

    // ═══════════════════════════════════════════════════════════════════
    //  Internal control: Lens Dial
    // ═══════════════════════════════════════════════════════════════════

    private sealed class LensDial : Control
    {
        public int CurrentPosition { get; set; }
        public float Proximity { get; set; }
        public bool IsLocked { get; set; }
        public bool IsHighlighted { get; set; }

        public event Action<bool>? OnRotated;

        public LensDial()
        {
            MinSize = new Vector2(56, 56);
            MouseFilter = MouseFilterMode.Stop;
        }

        protected override void KeyBindDown(GUIBoundKeyEventArgs args)
        {
            base.KeyBindDown(args);

            if (IsLocked)
                return;

            if (args.Function == EngineKeyFunctions.UIClick)
            {
                OnRotated?.Invoke(true);
                args.Handle();
            }
            else if (args.Function == EngineKeyFunctions.UIRightClick)
            {
                OnRotated?.Invoke(false);
                args.Handle();
            }
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var scale = UIScale;
            var center = new Vector2(PixelWidth / 2f, PixelHeight / 2f);
            var radius = 23f * scale;

            Color ringColor;
            if (IsLocked)
                ringColor = new Color(0.25f, 0.85f, 0.45f);
            else if (Proximity >= 1.0f)
                ringColor = new Color(0.25f, 0.85f, 0.45f);
            else if (Proximity >= 0.5f)
                ringColor = new Color(0.85f, 0.75f, 0.20f);
            else if (Proximity >= 0.2f)
                ringColor = new Color(0.55f, 0.40f, 0.15f);
            else
                ringColor = new Color(0.20f, 0.45f, 0.50f);

            // Animated glow for highlighted (current timing phase target)
            if (IsHighlighted)
            {
                handle.DrawCircle(center, radius + 6 * scale, new Color(0.9f, 0.7f, 0.1f, 0.25f));
                handle.DrawCircle(center, radius + 4 * scale, new Color(0.8f, 0.6f, 0.1f, 0.15f));
            }
            else if (IsLocked)
            {
                handle.DrawCircle(center, radius + 4 * scale, new Color(0.12f, 0.55f, 0.25f, 0.25f));
            }

            // Background
            handle.DrawCircle(center, radius + 1 * scale, new Color(0.10f, 0.14f, 0.20f));
            handle.DrawCircle(center, radius, new Color(0.04f, 0.06f, 0.09f));

            // Ring — double border for depth
            handle.DrawCircle(center, radius, ringColor, false);
            handle.DrawCircle(center, radius - 1 * scale, ringColor.WithAlpha(0.5f), false);

            // ─── Tick marks ───
            for (var i = 0; i < Positions; i++)
            {
                var angle = i * MathF.PI * 2 / Positions - MathF.PI / 2;
                var dir = new Vector2(MathF.Cos(angle), MathF.Sin(angle));
                var outer = center + dir * (radius - 2 * scale);
                var tickLen = (i % 3 == 0) ? 7f : 4f;
                var inner = center + dir * (radius - tickLen * scale);

                var tickColor = i == CurrentPosition
                    ? Color.White
                    : new Color(0.28f, 0.40f, 0.43f);

                handle.DrawLine(inner, outer, tickColor);
            }

            // ─── Pointer with bright tip ───
            var posAngle = CurrentPosition * MathF.PI * 2 / Positions - MathF.PI / 2;
            var posDir = new Vector2(MathF.Cos(posAngle), MathF.Sin(posAngle));

            // Pointer line
            handle.DrawLine(
                center + posDir * 4 * scale,
                center + posDir * (radius - 8 * scale),
                Color.White);

            // Pointer tip dot
            handle.DrawCircle(center + posDir * (radius - 9 * scale), 2.5f * scale, Color.White);

            // Center dot
            handle.DrawCircle(center, 3f * scale, new Color(0.08f, 0.10f, 0.14f));
            handle.DrawCircle(center, 2.5f * scale, ringColor);
        }
    }
}
