# DV - Item Quality Recipes

- type: latheRecipe
  id: WeaponRepairKit
  result: WeaponRepairKit
  completetime: 4
  materials:
    Steel: 500
    Plasteel: 200

- type: latheRecipe
  id: ClothingEyesGlassesAppraiser
  result: ClothingEyesGlassesAppraiser
  completetime: 3
  materials:
    Steel: 200
    Glass: 300
