using Content.Client.GameTicking.Managers;
using Content.Shared.PDA;
using Robust.Shared.Utility;
using Content.Shared.CartridgeLoader;
using Content.Client.Message;
using Content.Shared._NF.Bank;
using Content.Shared._Goobstation.StationRadio;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Timing;

namespace Content.Client.PDA
{
    [GenerateTypedNameReferences]
    public sealed partial class PdaMenu : PdaWindow
    {
        [Dependency] private readonly IClipboardManager _clipboard = null!;
        [Dependency] private readonly IGameTiming _gameTiming = default!;
        [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
        private readonly ClientGameTicker _gameTicker;

        public const int HomeView = 0;
        public const int ProgramListView = 1;
        public const int SettingsView = 2;
        public const int ProgramContentView = 3;


        private string _pdaOwner = Loc.GetString("comp-pda-ui-unknown");
        private string _owner = Loc.GetString("comp-pda-ui-unknown");
        private string _jobTitle = Loc.GetString("comp-pda-ui-unassigned");
        private string _stationName = Loc.GetString("comp-pda-ui-unknown");
        private string _alertLevel = Loc.GetString("comp-pda-ui-unknown");
        private string _instructions = Loc.GetString("comp-pda-ui-unknown");

        private string _balance = Loc.GetString("comp-pda-ui-unknown"); // Frontier
        private string _shuttleDeed = Loc.GetString("comp-pda-ui-unknown"); // Frontier

        private int _currentView;
        private bool _canPlayMusic;
        private bool _canListenStationRadio;
        private bool _stationRadioEnabled;
        private uint _stationRadioFrequency;
        private string? _stationRadioName;
        private bool _stationRadioScanning;
        private List<PdaStationRadioScanEntry> _stationRadioScanResults = new();
        private readonly List<(EntityUid, CartridgeComponent)> _availablePrograms = new();
        private PdaStationRadioProgram? _stationRadioProgram;
        private readonly List<(string LocKey, Color Color)> _screenColorPresets = new()
        {
            ("comp-pda-ui-screen-color-green", Color.FromHex("#4B8F5C")),
            ("comp-pda-ui-screen-color-amber", Color.FromHex("#A57F3D")),
            ("comp-pda-ui-screen-color-cyan", Color.FromHex("#4F8E90")),
            ("comp-pda-ui-screen-color-blue", Color.FromHex("#4A6E98")),
            ("comp-pda-ui-screen-color-phosphor", Color.FromHex("#6F9C62")),
            ("comp-pda-ui-screen-color-olive", Color.FromHex("#6C7D4A")),
            ("comp-pda-ui-screen-color-teal", Color.FromHex("#4A8274")),
            ("comp-pda-ui-screen-color-ice", Color.FromHex("#7A9B93")),
            ("comp-pda-ui-screen-color-mono", Color.FromHex("#8A8F88")),
            ("comp-pda-ui-screen-color-red", Color.FromHex("#8D5A57")),
        };

        public event Action<EntityUid>? OnProgramItemPressed;
        public event Action<EntityUid>? OnUninstallButtonPressed;
        public event Action<EntityUid>? OnInstallButtonPressed;
        public event Action? OnMusicProgramPressed;
        public event Action? OnStationRadioTogglePressed;
        public event Action<int>? OnStationRadioFrequencyChanged;
        public event Action? OnStationRadioScanRequested;
        public PdaMenu()
        {
            IoCManager.InjectDependencies(this);
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
            RobustXamlLoader.Load(this);

            ViewContainer.OnChildAdded += control => control.Visible = false;

            HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
            FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
            EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
            EjectBookButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/gavel.png"));
            EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
            EjectPaiButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pai.png"));
            ProgramCloseButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/cross.svg.png"));


            HomeButton.OnPressed += _ => ToHomeScreen();

            ProgramListButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = true;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = false;

                ChangeView(ProgramListView);
            };


            SettingsButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = true;
                ProgramTitle.IsCurrent = false;

                ChangeView(SettingsView);
            };

            ProgramTitle.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = true;

                ChangeView(ProgramContentView);
            };

            ProgramCloseButton.OnPressed += _ =>
            {
                HideProgramHeader();
                ToHomeScreen();
            };

            PdaOwnerButton.OnPressed += _ =>
            {
                _clipboard.SetText(_pdaOwner);
            };

            IdInfoButton.OnPressed += _ =>
            {
                _clipboard.SetText(_owner + ", " + _jobTitle);
            };

            StationNameButton.OnPressed += _ =>
            {
                _clipboard.SetText(_stationName);
            };

            StationAlertLevelButton.OnPressed += _ =>
            {
                _clipboard.SetText(_alertLevel);
            };

            // Frontier
            BalanceButton.OnPressed += _ =>
            {
                _clipboard.SetText(_balance);
            };
            ShuttleDeedButton.OnPressed += _ =>
            {
                _clipboard.SetText(_shuttleDeed);
            };
            // End Frontier

            StationTimeButton.OnPressed += _ =>
            {
                var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
                _clipboard.SetText((stationTime.ToString("hh\\:mm\\:ss")));
            };

            StationAlertLevelInstructionsButton.OnPressed += _ =>
            {
                _clipboard.SetText(_instructions);
            };

            for (var i = 0; i < _screenColorPresets.Count; i++)
            {
                var preset = _screenColorPresets[i];
                ScreenColorPresetButton.AddItem(Loc.GetString(preset.LocKey), i);
            }

            ScreenColorPresetButton.OnItemSelected += args =>
            {
                ScreenColorPresetButton.SelectId(args.Id);

                if (!_screenColorPresets.TryGetValue(args.Id, out var preset))
                    return;

                SetScreenTint(preset.Color);
            };

            ScreenColorPresetButton.SelectId(0);
            SetScreenTint(_screenColorPresets[0].Color);




            HideAllViews();
            ToHomeScreen();
        }

        public void UpdateState(PdaUpdateState state)
        {
            FlashLightToggleButton.IsActive = state.FlashlightEnabled;

            if (state.PdaOwnerInfo.ActualOwnerName != null)
            {
                _pdaOwner = state.PdaOwnerInfo.ActualOwnerName;

                // Check if we have company information to display
                if (!string.IsNullOrWhiteSpace(state.PdaOwnerInfo.CompanyName))
                {
                    PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner-with-company",
                        ("actualOwnerName", _pdaOwner),
                        ("companyName", state.PdaOwnerInfo.CompanyName),
                        ("companyColor", state.PdaOwnerInfo.CompanyColor.ToHex())));
                }
                else
                {
                    PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner",
                        ("actualOwnerName", _pdaOwner)));
                }
                PdaOwnerLabel.Visible = true;
            }
            else
            {
                PdaOwnerLabel.Visible = false;
            }


            if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
            {
                _owner = state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown");
                _jobTitle = state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned");
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui",
                    ("owner", _owner),
                    ("jobTitle", _jobTitle)));
            }
            else
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
            }

            _stationName = state.StationName ?? Loc.GetString("comp-pda-ui-unknown");
            StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station",
                ("station", _stationName)));

            _balance = BankSystemExtensions.ToSpesoString(state.Balance); // Frontier
            BalanceLabel.SetMarkup(Loc.GetString("comp-pda-ui-balance", ("balance", _balance))); // Frontier

            _shuttleDeed = state.OwnedShipName ?? ""; // Frontier
            ShuttleDeedLabel.SetMarkup(Loc.GetString("comp-pda-ui-shuttle-deed", ("shipname", _shuttleDeed))); // Frontier
            ShuttleDeedLabel.Visible = !string.IsNullOrEmpty(state.OwnedShipName); // Frontier

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));

            var alertLevel = state.PdaOwnerInfo.StationAlertLevel;
            var alertColor = state.PdaOwnerInfo.StationAlertColor;
            var alertLevelKey = alertLevel != null ? $"alert-level-{alertLevel}" : "alert-level-unknown";
            _alertLevel = Loc.GetString(alertLevelKey);

            StationAlertLevelLabel.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level",
                ("color", alertColor),
                ("level", _alertLevel)
            ));
            _instructions = Loc.GetString($"{alertLevelKey}-instructions");
            StationAlertLevelInstructions.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level-instructions",
                ("instructions", _instructions))
            );

            AddressLabel.Text = state.Address?.ToUpper() ?? " - ";

            EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
            EjectPenButton.IsActive = state.HasPen;
            EjectPaiButton.IsActive = state.HasPai;

            var shouldRebuildPrograms = _canPlayMusic != state.CanPlayMusic
                                        || _canListenStationRadio != state.CanListenStationRadio;

            _canPlayMusic = state.CanPlayMusic;
            _canListenStationRadio = state.CanListenStationRadio;
            _stationRadioEnabled = state.StationRadioEnabled;
            _stationRadioFrequency = state.StationRadioFrequency;
            _stationRadioName = state.StationRadioName;
            _stationRadioScanning = state.StationRadioScanning;
            _stationRadioScanResults = state.StationRadioScanResults;

            if (_stationRadioProgram != null)
                _stationRadioProgram.UpdateState(_stationRadioEnabled,
                    _stationRadioFrequency,
                    _stationRadioName,
                    _stationRadioScanning,
                    _stationRadioScanResults);

                if (shouldRebuildPrograms)
                    RebuildPrograms();

            ShowUplinkButton.Visible = state.HasUplink;
            LockUplinkButton.Visible = state.HasUplink;
        }

        public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
        {
            _availablePrograms.Clear();
            _availablePrograms.AddRange(programs);
            RebuildPrograms();
        }

        private void RebuildPrograms()
        {
            ProgramList.RemoveAllChildren();

            AddBuiltInPrograms();

            if (_availablePrograms.Count == 0)
            {
                if (!_canPlayMusic && !_canListenStationRadio)
                {
                    ProgramList.AddChild(new Label()
                    {
                        Text = Loc.GetString("comp-pda-io-no-programs-available"),
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        VerticalExpand = true
                    });
                }

                return;
            }

            var row = CreateProgramListRow();
            var itemCount = 1;
            ProgramList.AddChild(row);

            foreach (var (uid, component) in _availablePrograms)
            {
                if (itemCount % 2 != 0)
                {
                    row = CreateProgramListRow();
                    ProgramList.AddChild(row);
                }

                var item = new PdaProgramItem();

                if (component.Icon is not null)
                    item.Icon.SetFromSpriteSpecifier(component.Icon);

                item.OnPressed += _ => OnProgramItemPressed?.Invoke(uid);

                switch (component.InstallationStatus)
                {
                    case InstallationStatus.Cartridge:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                        item.InstallButton.OnPressed += _ => OnInstallButtonPressed?.Invoke(uid);
                        break;
                    case InstallationStatus.Installed:
                        item.InstallButton.Visible = true;
                        item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                        item.InstallButton.OnPressed += _ => OnUninstallButtonPressed?.Invoke(uid);
                        break;
                }

                item.ProgramName.Text = Loc.GetString(component.ProgramName);
                item.SetHeight = 20;
                row.AddChild(item);

                itemCount++;
            }

            if (itemCount % 2 == 0)
                row.AddChild(new Control() { HorizontalExpand = true });
        }

        private void AddBuiltInPrograms()
        {
            if (_canListenStationRadio)
            {
                var stationRadioProgram = new PdaProgramItem();
                stationRadioProgram.Icon.SetFromSpriteSpecifier(new SpriteSpecifier.Texture(new ResPath("/Textures/Objects/Devices/communication.rsi/radio.png")));
                stationRadioProgram.ProgramName.Text = Loc.GetString("pda-program-radio-short");
                stationRadioProgram.InstallButton.Visible = false;
                stationRadioProgram.SetHeight = 20;

                stationRadioProgram.OnPressed += _ => OpenStationRadioProgram();
                ProgramList.AddChild(stationRadioProgram);
            }

            if (_canPlayMusic)
            {
                var musicProgram = new PdaProgramItem();
                musicProgram.Icon.SetFromSpriteSpecifier(new SpriteSpecifier.Texture(new ResPath("/Textures/Objects/Fun/Instruments/accordion.rsi/icon.png")));
                musicProgram.ProgramName.Text = Loc.GetString("pda-program-music-title");
                musicProgram.InstallButton.Visible = false;
                musicProgram.SetHeight = 20;

                musicProgram.OnPressed += _ => OnMusicProgramPressed?.Invoke();
                ProgramList.AddChild(musicProgram);
            }
        }

        private void OpenStationRadioProgram()
        {
            ProgramView.RemoveAllChildren();

            _stationRadioProgram = new PdaStationRadioProgram();
            _stationRadioProgram.OnToggleListening += () => OnStationRadioTogglePressed?.Invoke();
            _stationRadioProgram.OnFrequencyChanged += value => OnStationRadioFrequencyChanged?.Invoke(value);
            _stationRadioProgram.OnScanRequested += () => OnStationRadioScanRequested?.Invoke();
            _stationRadioProgram.OnScanResultSelected += value => OnStationRadioFrequencyChanged?.Invoke(value);
            _stationRadioProgram.UpdateState(_stationRadioEnabled,
                _stationRadioFrequency,
                _stationRadioName,
                _stationRadioScanning,
                _stationRadioScanResults);

            ProgramView.AddChild(_stationRadioProgram);
            ToProgramView(Loc.GetString("pda-program-station-radio-title"));
        }

        /// <summary>
        /// Changes the current view to the home screen (view 0) and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToHomeScreen()
        {
            HomeButton.IsCurrent = true;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;

            ChangeView(HomeView);
        }

        /// <summary>
        /// Hides the program title and close button.
        /// </summary>
        public void HideProgramHeader()
        {
            ProgramTitle.IsCurrent = false;
            ProgramTitle.Visible = false;
            ProgramCloseButton.Visible = false;
            ProgramListButton.Visible = true;
            SettingsButton.Visible = true;
        }

        /// <summary>
        /// Changes the current view to the program content view (view 3), sets the program title and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToProgramView(string title)
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            ProgramTitle.IsCurrent = true;
            ProgramTitle.Visible = true;
            ProgramCloseButton.Visible = true;
            ProgramListButton.Visible = false;
            SettingsButton.Visible = false;

            ProgramTitle.LabelText = title;
            ChangeView(ProgramContentView);
        }


        /// <summary>
        /// Changes the current view to the given view number
        /// </summary>
        public void ChangeView(int view)
        {
            if (ViewContainer.ChildCount <= view)
                return;

            ViewContainer.GetChild(_currentView).Visible = false;
            ViewContainer.GetChild(view).Visible = true;
            _currentView = view;
        }

        private static BoxContainer CreateProgramListRow()
        {
            return new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };
        }

        private void HideAllViews()
        {
            var views = ViewContainer.Children;
            foreach (var view in views)
            {
                view.Visible = false;
            }
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));
        }
    }
}
