using Content.Shared.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaStationRadioProgram : BoxContainer
{
    public event Action<int>? OnFrequencyChanged;
    public event Action? OnToggleListening;
    public event Action? OnScanRequested;
    public event Action<int>? OnScanResultSelected;

    private int _frequency;
    private bool _suppressEvents;
    private int? _lastSentFrequency;

    public PdaStationRadioProgram()
    {
        RobustXamlLoader.Load(this);

        FrequencyLineEdit.OnTextEntered += e => TrySendFrequency(e.Text);
        FrequencyLineEdit.OnFocusExit += e => TrySendFrequency(e.Text);

        FrequencyDownButton.OnPressed += _ => OnFrequencyChanged?.Invoke(_frequency - 1);
        FrequencyUpButton.OnPressed += _ => OnFrequencyChanged?.Invoke(_frequency + 1);
        FrequencySlider.OnValueChanged += _ =>
        {
            if (_suppressEvents)
                return;

            EmitFrequencyChanged((int) FrequencySlider.Value);
        };

        ToggleListeningButton.OnPressed += _ => OnToggleListening?.Invoke();
        ScanButton.OnPressed += _ => OnScanRequested?.Invoke();
        ScanResultsList.OnItemSelected += args =>
        {
            if (args.ItemIndex < 0 || args.ItemIndex >= args.ItemList.Count)
                return;

            if (args.ItemList[args.ItemIndex].Metadata is int frequency)
                OnScanResultSelected?.Invoke(frequency);
        };
    }

    public void UpdateState(bool enabled, uint frequency, string? stationName, bool scanning, List<PdaStationRadioScanEntry> scanResults)
    {
        _suppressEvents = true;
        _frequency = (int) frequency;
        _lastSentFrequency = _frequency;
        FrequencyLineEdit.Text = frequency.ToString();
        FrequencySlider.Value = frequency;
        ToggleListeningButton.Pressed = enabled;
        ToggleListeningButton.Text = Loc.GetString(enabled
            ? "pda-program-station-radio-listening-on"
            : "pda-program-station-radio-listening-off");

        StationNameLabel.Text = stationName == null
            ? Loc.GetString("pda-program-station-radio-no-signal")
            : Loc.GetString("pda-program-station-radio-current", ("name", stationName), ("frequency", frequency));

        ScanButton.Text = Loc.GetString(scanning
            ? "pda-program-station-radio-scanning"
            : "pda-program-station-radio-scan");
        ScanButton.Disabled = scanning;

        ScanResultsList.Clear();
        foreach (var entry in scanResults)
        {
            var item = new ItemList.Item(ScanResultsList)
            {
                Text = Loc.GetString("pda-program-station-radio-result", ("name", entry.Name), ("frequency", entry.Frequency)),
                Metadata = (int) entry.Frequency
            };
            ScanResultsList.Add(item);
        }

        _suppressEvents = false;
    }

    private void TrySendFrequency(string text)
    {
        if (int.TryParse(text.Trim(), out var value))
            EmitFrequencyChanged(value);
    }

    private void EmitFrequencyChanged(int value)
    {
        if (_lastSentFrequency == value)
            return;

        _lastSentFrequency = value;
        OnFrequencyChanged?.Invoke(value);
    }
}
