using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private ShaderInstance _crtShader = default!;
    private ShaderInstance _bloomShader = default!;


    public string? BorderColor
    {
        get => Background.ActualModulateSelf.ToHex();

        set => Background.ModulateSelfOverride = Color.FromHex(value, Color.White);
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();

        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();

        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    public PdaWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _crtShader = _prototypeManager.Index<ShaderPrototype>("PdaCrtOverlay").Instance().Duplicate();
        _bloomShader = _prototypeManager.Index<ShaderPrototype>("PdaSoftBloom").Instance().Duplicate();

        ScreenEffectOverlay.ShaderOverride = _crtShader;
        ScreenGlowOverlay.ShaderOverride = _bloomShader;
        ScreenGlowOverlay.ModulateSelfOverride = new Color(1f, 1f, 1f, 0.62f);
        ScreenGlowOverlay.Visible = true;

        SetScreenTint(Color.FromHex("#4B8F5C"));

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }

    public void SetScreenTint(Color color)
    {
        var tint = new Robust.Shared.Maths.Vector3(color.R, color.G, color.B);

        _crtShader.SetParameter("screen_tint", tint);
        _bloomShader.SetParameter("bloom_tint", tint);
    }
}
