using Content.Client.UserInterface.Controls;
using Content.Shared._Goobstation.StationRadio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Goobstation.StationRadio.UI;

[GenerateTypedNameReferences]
public sealed partial class StationRadioMenu : FancyWindow
{
    public event Action<string>? OnFrequencyChanged;
    public event Action<bool>? OnActiveToggled;
    public event Action<string>? OnBroadcastNameChanged;

    public StationRadioMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        FrequencyLineEdit.OnTextEntered += e => OnFrequencyChanged?.Invoke(e.Text);
        FrequencyLineEdit.OnFocusExit += e => OnFrequencyChanged?.Invoke(e.Text);
        BroadcastNameLineEdit.OnTextEntered += e => OnBroadcastNameChanged?.Invoke(e.Text);
        BroadcastNameLineEdit.OnFocusExit += e => OnBroadcastNameChanged?.Invoke(e.Text);
        ActiveButton.OnPressed += e => OnActiveToggled?.Invoke(e.Button.Pressed);
    }

    public void UpdateState(StationRadioBoundUiState state)
    {
        FrequencyLineEdit.Text = state.Frequency.ToString();

        var canEditName = state.CanEditBroadcastName;
        BroadcastNameLabel.Visible = canEditName;
        BroadcastNameLineEdit.Visible = canEditName;
        if (canEditName)
            BroadcastNameLineEdit.Text = state.BroadcastName ?? string.Empty;

        if (state.Active == null)
        {
            ActiveButton.Visible = false;
            return;
        }

        ActiveButton.Visible = true;
        ActiveButton.Pressed = state.Active.Value;
    }
}
